# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 
      uses: actions/setup-node@v1
    - run: |  
        node -v
        la -la  
        cat README.md 
    - name: Checkout submodule
      # You may pin to the exact commit or the version.
      # uses: Mushus/checkout-submodule@f6a7fddc9798c8f8728b252594243ced3b56e550
      uses: Mushus/checkout-submodule@v1.0.1
      with:
        # A path to execute git operation
        basePath: blogs # optional, default is .
        # A path of submodule directory
        submodulePath: blog
        # A identifier secret key to used checkout the submodule
        identifierFile: ${{secrets.TOKEN}} 
        

